Category.create(name: "Frozen Foods")
Category.create(name: "Drinks & Beverages")
Category.create(name: "School & Office Items")
Category.create(name: "Household Care")
Category.create(name: "Canned/Jarred Goods & Dairy")
Category.create(name: "Snacks & Candies")
Category.create(name: "Health & Beauty")
Category.create(name: "Hardware Items")
Category.create(name: "Gas, Oils & Lubricants")
Category.create(name: "Agricultural Items")
Category.create(name: "Apparels")
Category.create(name: "Miscellaneous")