# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: itworx_pos_final_development

test:
  <<: *default
  database: itworx_pos_final_test

production:
  <<: *default
  database: itworx_pos_final_production
  username: deploy
  password: <%= ENV['ITWORX_POS_FINAL_DATABASE_PASSWORD'] %>
